sed -ie "/^aaroncastellanos_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\aaroncastellanos_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^alejoledesma_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\alejoledesma_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^ambrosetti_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\ambrosetti_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^amenabar_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\amenabar_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^angeloni_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\angeloni_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^apeaderoarrascaeta_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\apeaderoarrascaeta_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^arequito_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\arequito_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^armstrong_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\armstrong_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^arocena_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\arocena_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^arroyoaguiar_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\arroyoaguiar_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^arroyojuarez_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\arroyojuarez_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^arroyolastortugas_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\arroyolastortugas_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^arroyosanantonio_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\arroyosanantonio_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^arrufo_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\arrufo_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^ascochinga_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\ascochinga_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^aurelia_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\aurelia_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^barrancas_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\barrancas_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^benjamingould_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\benjamingould_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^bernardodeirigoyen_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\bernardodeirigoyen_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^bigand_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\bigand_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^bossi_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\bossi_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^bustinza_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\bustinza_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^cafferata_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\cafferata_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^campoandino_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\campoandino_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^canalsanantonio_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\canalsanantonio_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^candioti_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\candioti_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^carlospellegrini_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\carlospellegrini_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^casilda_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\casilda_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^castellanos_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\castellanos_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^cayasta_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\cayasta_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^chabas_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\chabas_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^chilca_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\chilca_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^chovet_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\chovet_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^clason_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\clason_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^colastine_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\colastine_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^coloniaalpina_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\coloniaalpina_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^coloniacastelar_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\coloniacastelar_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^coloniamackinley_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\coloniamackinley_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^coloniamendigueren_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\coloniamendigueren_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^coloniamoreno_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\coloniamoreno_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^coloniaprogreso_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\coloniaprogreso_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^coloniarosa_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\coloniarosa_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^coloniateresa_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\coloniateresa_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^constituyentes_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\constituyentes_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^coronda_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\coronda_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^correa_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\correa_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^crispi_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\crispi_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^cululu_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\cululu_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^curupayti_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\curupayti_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^delgado_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\delgado_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^diaz_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\diaz_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^divisademayo_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\divisademayo_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^dosprovincias_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\dosprovincias_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^elabolengo_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\elabolengo_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^elarbolito_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\elarbolito_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^elcantor_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\elcantor_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^ellaurel_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\ellaurel_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^elmocoreta_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\elmocoreta_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^elpedernal_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\elpedernal_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^elrecuerdo_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\elrecuerdo_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^eltrebol_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\eltrebol_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^esperanza_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\esperanza_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^estanciasantaana_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\estanciasantaana_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^eusebia_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\eusebia_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^faustina_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\faustina_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^fortintiburcio_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\fortintiburcio_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^gaboto_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\gaboto_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^gelly_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\gelly_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^gessler_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\gessler_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^guatimozin_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\guatimozin_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^hansen_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\hansen_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^helvecia_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\helvecia_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^hersilia_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\hersilia_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^huemul_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\huemul_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^hughes_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\hughes_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^humboldt_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\humboldt_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^jacinto_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\jacinto_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^juncal_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\juncal_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^laalpina_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\laalpina_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lacurva_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lacurva_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^laelena_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\laelena_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^laesmeralda_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\laesmeralda_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^laflorida_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\laflorida_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lagerda_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lagerda_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lagermania_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lagermania_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^laindiada_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\laindiada_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^laleoncita_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\laleoncita_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^landeta_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\landeta_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lapatria_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lapatria_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lapelada_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lapelada_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^larivieri_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\larivieri_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^larubia_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\larubia_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lasbandurrias_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lasbandurrias_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lasgamas_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lasgamas_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^laspalmeras_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\laspalmeras_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lasparvas_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lasparvas_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lasprusianas_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lasprusianas_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lastunas_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lastunas_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lasturbias_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lasturbias_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lazoraida_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lazoraida_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lazzarino_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lazzarino_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lehmann_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lehmann_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lima_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lima_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lomaalta_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lomaalta_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^loscardos_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\loscardos_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^loscerillos_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\loscerillos_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^loscharabones_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\loscharabones_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^losmedanitos_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\losmedanitos_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lucianoleiva_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lucianoleiva_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^maciel_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\maciel_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^maggiolo_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\maggiolo_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^maizales_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\maizales_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^manantiales_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\manantiales_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^marialuisa_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\marialuisa_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^matilde_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\matilde_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^melincue_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\melincue_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^monigotes_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\monigotes_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^monteoscuridad_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\monteoscuridad_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^murphy_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\murphy_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^oliveros_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\oliveros_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^paikin_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\paikin_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^pergamino_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\pergamino_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^petronila_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\petronila_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^peyrano_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\peyrano_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^Pilar_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\Pilar_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^pueblocasas_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\pueblocasas_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^pueblodeirigoyen_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\pueblodeirigoyen_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^puebloelisa_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\puebloelisa_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^rafaela_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\rafaela_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^ramallo_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\ramallo_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^ramona_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\ramona_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^rancagua_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\rancagua_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^Recreo_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\Recreo_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^rincondeavila_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\rincondeavila_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^riosalado_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\riosalado_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^rojas_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\rojas_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^saforcada_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\saforcada_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^sanantonio_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\sanantonio_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^sanbernardo_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\sanbernardo_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^sanjusto_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\sanjusto_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^sanmartindelasescobas_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\sanmartindelasescobas_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^sanpedro_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\sanpedro_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^santafilipina_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\santafilipina_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^santaisabel_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\santaisabel_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^santamarianorte_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\santamarianorte_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^sastre_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\sastre_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^schiffner_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\schiffner_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^serodino_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\serodino_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^soldemayo_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\soldemayo_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^teodelina_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\teodelina_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^totoras_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\totoras_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^tresreyes_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\tresreyes_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^treslagunas_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\treslagunas_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^venadotuerto_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\venadotuerto_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^videla_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\videla_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^vila_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\vila_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^villada_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\villada_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^villaeloisa_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\villaeloisa_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^wheelwright_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\wheelwright_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^zavalla_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\zavalla_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^apeaderomascias_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\apeaderomascias_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^caciqueariacaiquin_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\caciqueariacaiquin_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^canadadelucle_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\canadadelucle_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^estanciasantaana_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\estanciasantaana_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lasarita_descripcion_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lasarita_descripcion_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^lasofia_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\lasofia_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^marcojuarezi_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\marcojuarezi_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^mariamanuela_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\mariamanuela_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^mariateresa_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\mariateresa_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^namuncura_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\namuncura_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^orono_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\orono_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^roldan_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\roldan_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^rosales_descripcion_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\rosales_descripcion_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^sanctispiritu_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\sanctispiritu_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^sanfabian_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\sanfabian_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^sanguillermo_descripcion_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\sanguillermo_descripcion_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^sanjulian_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\sanjulian_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^santalucia_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\santalucia_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^villacanas_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\villacanas_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^villarosi_descripcion_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\villarosi_descripcion_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
sed -ie "/^villatrinidad_descripcion_datos_analiticos.psv ->> HORIZONTE->RESIST. PASTA/a\\villatrinidad_descripcion_datos_analiticos.psv ->> HORIZONTE->CONDUCT mmhos\/cm.:" santa-fe_series_v1.1.txt
