sed -ie "/^aaroncastellanos_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\aaroncastellanos_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^alejoledesma_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\alejoledesma_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^ambrosetti_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\ambrosetti_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^amenabar_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\amenabar_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^angeloni_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\angeloni_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^apeaderoarrascaeta_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\apeaderoarrascaeta_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^arequito_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\arequito_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^armstrong_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\armstrong_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^arocena_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\arocena_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^arroyoaguiar_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\arroyoaguiar_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^arroyojuarez_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\arroyojuarez_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^arroyolastortugas_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\arroyolastortugas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^arroyosanantonio_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\arroyosanantonio_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^arrufo_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\arrufo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^ascochinga_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\ascochinga_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^aurelia_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\aurelia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^barrancas_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\barrancas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^benjamingould_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\benjamingould_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^bernardodeirigoyen_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\bernardodeirigoyen_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^bigand_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\bigand_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^bossi_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\bossi_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^bustinza_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\bustinza_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^cafferata_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\cafferata_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^campoandino_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\campoandino_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^canalsanantonio_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\canalsanantonio_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^candioti_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\candioti_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^carlospellegrini_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\carlospellegrini_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^casilda_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\casilda_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^castellanos_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\castellanos_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^cayasta_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\cayasta_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^chabas_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\chabas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^chilca_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\chilca_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^chovet_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\chovet_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^clason_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\clason_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^colastine_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\colastine_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^coloniaalpina_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\coloniaalpina_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^coloniacastelar_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\coloniacastelar_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^coloniamackinley_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\coloniamackinley_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^coloniamendigueren_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\coloniamendigueren_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^coloniamoreno_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\coloniamoreno_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^coloniaprogreso_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\coloniaprogreso_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^coloniarosa_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\coloniarosa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^coloniateresa_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\coloniateresa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^constituyentes_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\constituyentes_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^coronda_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\coronda_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^correa_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\correa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^crispi_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\crispi_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^cululu_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\cululu_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^curupayti_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\curupayti_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^delgado_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\delgado_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^diaz_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\diaz_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^divisademayo_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\divisademayo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^dosprovincias_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\dosprovincias_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^elabolengo_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\elabolengo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^elarbolito_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\elarbolito_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^elcantor_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\elcantor_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^ellaurel_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\ellaurel_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^elmocoreta_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\elmocoreta_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^elpedernal_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\elpedernal_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^elrecuerdo_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\elrecuerdo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^eltrebol_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\eltrebol_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^esperanza_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\esperanza_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^estanciasantaana_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\estanciasantaana_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^eusebia_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\eusebia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^faustina_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\faustina_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^fortintiburcio_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\fortintiburcio_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^gaboto_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\gaboto_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^gelly_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\gelly_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^gessler_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\gessler_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^guatimozin_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\guatimozin_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^hansen_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\hansen_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^helvecia_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\helvecia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^hersilia_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\hersilia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^huemul_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\huemul_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^hughes_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\hughes_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^humboldt_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\humboldt_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^jacinto_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\jacinto_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^juncal_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\juncal_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^laalpina_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\laalpina_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lacurva_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lacurva_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^laelena_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\laelena_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^laesmeralda_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\laesmeralda_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^laflorida_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\laflorida_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lagerda_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lagerda_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lagermania_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lagermania_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^laindiada_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\laindiada_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^laleoncita_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\laleoncita_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^landeta_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\landeta_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lapatria_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lapatria_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lapelada_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lapelada_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^larivieri_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\larivieri_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^larubia_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\larubia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lasbandurrias_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lasbandurrias_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lasgamas_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lasgamas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^laspalmeras_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\laspalmeras_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lasparvas_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lasparvas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lasprusianas_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lasprusianas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lastunas_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lastunas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lasturbias_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lasturbias_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lazoraida_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lazoraida_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lazzarino_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lazzarino_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lehmann_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lehmann_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lima_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lima_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lomaalta_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lomaalta_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^loscardos_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\loscardos_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^loscerillos_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\loscerillos_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^loscharabones_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\loscharabones_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^losmedanitos_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\losmedanitos_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lucianoleiva_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lucianoleiva_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^maciel_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\maciel_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^maggiolo_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\maggiolo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^maizales_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\maizales_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^manantiales_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\manantiales_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^marialuisa_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\marialuisa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^matilde_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\matilde_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^melincue_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\melincue_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^monigotes_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\monigotes_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^monteoscuridad_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\monteoscuridad_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^murphy_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\murphy_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^oliveros_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\oliveros_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^paikin_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\paikin_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^pergamino_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\pergamino_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^petronila_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\petronila_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^peyrano_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\peyrano_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^Pilar_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\Pilar_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^pueblocasas_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\pueblocasas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^pueblodeirigoyen_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\pueblodeirigoyen_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^puebloelisa_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\puebloelisa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^rafaela_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\rafaela_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^ramallo_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\ramallo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^ramona_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\ramona_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^rancagua_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\rancagua_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^Recreo_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\Recreo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^rincondeavila_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\rincondeavila_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^riosalado_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\riosalado_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^rojas_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\rojas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^saforcada_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\saforcada_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^sanantonio_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\sanantonio_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^sanbernardo_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\sanbernardo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^sanjusto_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\sanjusto_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^sanmartindelasescobas_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\sanmartindelasescobas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^sanpedro_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\sanpedro_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^santafilipina_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\santafilipina_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^santaisabel_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\santaisabel_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^santamarianorte_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\santamarianorte_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^sastre_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\sastre_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^schiffner_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\schiffner_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^serodino_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\serodino_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^soldemayo_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\soldemayo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^teodelina_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\teodelina_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^totoras_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\totoras_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^tresreyes_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\tresreyes_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^treslagunas_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\treslagunas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^venadotuerto_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\venadotuerto_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^videla_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\videla_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^vila_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\vila_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^villada_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\villada_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^villaeloisa_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\villaeloisa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^wheelwright_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\wheelwright_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^zavalla_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\zavalla_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^apeaderomascias_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\apeaderomascias_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^caciqueariacaiquin_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\caciqueariacaiquin_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^canadadelucle_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\canadadelucle_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^estanciasantaana_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\estanciasantaana_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lasarita_descripcion_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lasarita_descripcion_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^lasofia_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\lasofia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^marcojuarezi_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\marcojuarezi_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^mariamanuela_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\mariamanuela_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^mariateresa_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\mariateresa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^namuncura_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\namuncura_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^orono_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\orono_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^roldan_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\roldan_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^rosales_descripcion_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\rosales_descripcion_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^sanctispiritu_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\sanctispiritu_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^sanfabian_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\sanfabian_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^sanguillermo_descripcion_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\sanguillermo_descripcion_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^sanjulian_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\sanjulian_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^santalucia_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\santalucia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^villacanas_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\villacanas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^villarosi_descripcion_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\villarosi_descripcion_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
sed -ie "/^villatrinidad_descripcion_datos_analiticos.psv ->> HORIZONTE->LIMO 2-50 (%)/a\\villatrinidad_descripcion_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:" santa-fe_series_v1.1.txt
