aaroncastellanos_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
alejoledesma_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
ambrosetti_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
amenabar_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
angeloni_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
apeaderoarrascaeta_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
arequito_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
armstrong_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
arocena_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
arroyoaguiar_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
arroyojuarez_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
arroyolastortugas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
arroyosanantonio_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
arrufo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
ascochinga_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
aurelia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
barrancas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
benjamingould_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
bernardodeirigoyen_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
bigand_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
bossi_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
bustinza_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
cafferata_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
campoandino_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
canalsanantonio_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
candioti_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
carlospellegrini_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
casilda_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
castellanos_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
cayasta_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
chabas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
chilca_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
chovet_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
clason_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
colastine_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
coloniaalpina_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
coloniacastelar_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
coloniamackinley_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
coloniamendigueren_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
coloniamoreno_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
coloniaprogreso_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
coloniarosa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
coloniateresa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
constituyentes_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
coronda_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
correa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
crispi_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
cululu_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
curupayti_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
delgado_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
diaz_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
divisademayo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
dosprovincias_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
elabolengo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
elarbolito_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
elcantor_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
ellaurel_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
elmocoreta_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
elpedernal_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
elrecuerdo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
eltrebol_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
esperanza_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
estanciasantaana_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
eusebia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
faustina_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
fortintiburcio_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
gaboto_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
gelly_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
gessler_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
guatimozin_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
hansen_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
helvecia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
hersilia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
huemul_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
hughes_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
humboldt_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
jacinto_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
juncal_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
laalpina_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lacurva_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
laelena_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
laesmeralda_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
laflorida_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lagerda_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lagermania_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
laindiada_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
laleoncita_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
landeta_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lapatria_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lapelada_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
larivieri_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
larubia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lasbandurrias_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lasgamas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
laspalmeras_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lasparvas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lasprusianas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lastunas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lasturbias_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lazoraida_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lazzarino_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lehmann_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lima_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lomaalta_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
loscardos_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
loscerillos_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
loscharabones_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
losmedanitos_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lucianoleiva_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
maciel_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
maggiolo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
maizales_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
manantiales_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
marialuisa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
matilde_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
melincue_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
monigotes_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
monteoscuridad_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
murphy_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
oliveros_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
paikin_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
pergamino_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
petronila_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
peyrano_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
Pilar_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
pueblocasas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
pueblodeirigoyen_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
puebloelisa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
rafaela_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
ramallo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
ramona_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
rancagua_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
Recreo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
rincondeavila_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
riosalado_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
rojas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
saforcada_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
sanantonio_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
sanbernardo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
sanjusto_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
sanmartindelasescobas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
sanpedro_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
santafilipina_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
santaisabel_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
santamarianorte_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
sastre_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
schiffner_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
serodino_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
soldemayo_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
teodelina_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
totoras_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
tresreyes_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
treslagunas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
venadotuerto_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
videla_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
vila_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
villada_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
villaeloisa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
wheelwright_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
zavalla_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
apeaderomascias_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
caciqueariacaiquin_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
canadadelucle_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
estanciasantaana_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lasarita_descripcion_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
lasofia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
marcojuarezi_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
mariamanuela_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
mariateresa_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
namuncura_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
orono_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
roldan_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
rosales_descripcion_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
sanctispiritu_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
sanfabian_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
sanguillermo_descripcion_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
sanjulian_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
santalucia_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
villacanas_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
villarosi_descripcion_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
villatrinidad_descripcion_datos_analiticos.psv ->> HORIZONTE->ARENA >50µ.......:'" santa-fe_series_v1.1.txt
